export { default as ProductDetails } from "./ProductDetail/ProductDetail"
export { default as Home} from "./Home/Home"
export { default as Shop} from "./Shop/Shop"
export { default as Login} from "./Login/Login"
export { default as SignUp} from "./SignUp/SignUp"
export { default as Checkout} from "./Checkout/Checkout"
export { default as Contact} from "./Contact/Contact"
export { default as About} from "./About/About"
